#!/bin/sh
#BEGINN INIT INFO
# Provides:          playframework
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop playframework
### END INIT INFO
#
#source some script files in order to set and export environmental variables
#as well as add the appropriate executables to $PATH
 
APP_HOME='/home/cubrik/application/'
export PIDFILE='/home/cubrik/application/RUNNING_PID'
USER=playframework
GROUP=nogroup
 
case "$1" in
    start)
        echo "Starting playframework"
        START_CMD="${APP_HOME}/target/start"
        start-stop-daemon --start -p "${PIDFILE}" --quiet --background  --exec /bin/bash -- ${START_CMD}
        ;;
    stop)
        echo "Stopping playframework"
        kill -TERM $(cat "${APP_HOME}"/RUNNING_PID);;
      *)
        echo "Usage: /etc/init.d/playframework {start|stop}"
        exit 1
    ;;
esac
 
exit 0
